services:
  - type: web
    name: gafurjon-malumot
    runtime: node
    plan: free
    region: virginia
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
