const skills = ["HTML", "CSS", "JavaScript", "Node.js", "PHP", "SQL", "MySQL", "C# / .NET", "PostgreSQL", "GitHub", "Render"];

const projects = [
  { tag: "МАҲСУЛОТИ АСОСӢ", name: "TOJ POS", text: "Системаи автоматизатсияи кафе, ошхона, мағоза ва дорухона. Фурӯш, анбор, кассирҳо, смена, хароҷот, қарз ва фоида дар як барнома — бо назорат аз телефон ва бе пардохти ҳармоҳа.", tech: "C# · .NET 8 · MySQL · PostgreSQL · Cloud API", image: "/tojpos-cashier-web.jpg", featured: true },
  { tag: "ПЛАТФОРМАИ ИДОРАКУНӢ", name: "TOJ ERP", text: "Платформаи вебӣ барои идоракунии пурраи тиҷорат: назорати амалиётҳо, кормандон, маблағҳо, ҳисобот ва маълумоти марказӣ аз як панел. Лоиҳа аз сифр сохта шуда, дар GitHub нигоҳдорӣ ва дар Render ҷойгир шудааст.", tech: "Web · Database · GitHub · Render", image: "/toj-erp-web.png" },
  { tag: "ЧОП ВА АВТОМАТИЗАТСИЯ", name: "DataMatrixPro", text: "Барномаи Windows барои гирифтани маълумот аз Excel ва PDF, сохтани Data Matrix ва чоп дар принтерҳои Xprinter. Интихоби сабтҳо ва чопи гурӯҳӣ дастгирӣ мешавад.", tech: "C# · .NET 8 · WinForms · ZXing", image: "/datamatrixpro-web.jpg" },
  { tag: "ЧОПИ НИШОНАҲО", name: "MatrixPrint / LabelPrinter", text: "Системаи касбии QR/Data Matrix ва чопи TSPL бо коркарди CSV/PDF, танзими андозаи этикетка, идораи муштариён, SQLite ва механизми иҷозатномадиҳӣ.", tech: "C# · WPF · SQLite · SkiaSharp · TSPL", image: "/matrixprint-web.jpg" },
  { tag: "МОЛИЯИ ШАХСӢ", name: "Лотҳаи зиндагӣ", text: "Барномаи идоракунии молия, даромад, хароҷот, нақшаҳо ва корҳои рӯзмарра — барои дидани ҳолати умумии зиндагӣ дар як ҷой.", tech: "Personal finance · Planning" },
  { tag: "МОБИЛӢ", name: "English Learning", text: "Лоиҳаи омӯзиши забони англисӣ барои телефон, ки омӯзиши ҳаррӯзаро ба тарзи сода ва дастрас ташкил мекунад.", tech: "Mobile · Education" },
];

export default function Home() {
  return <main>
    <nav className="nav shell"><a className="brand" href="#top"><span>GF</span> Ғафурҷон</a><div className="navlinks"><a href="#about">Дар бораи ман</a><a href="#projects">Лоиҳаҳо</a><a href="#journey">Роҳи касбӣ</a><a href="#contact">Тамос</a></div></nav>
    <section className="hero shell" id="top">
      <div><p className="eyebrow"><i/> Барномасоз · Муҳандис · Созандаи маҳсулот</p><h1>Ғафурҷон<br/><em>Уайдулоев</em></h1><p className="lead">Ман системаҳои воқеиро барои автоматизатсияи тиҷорат месозам — аз барномаҳои офлайнӣ то платформаҳои абрӣ, ки аз ҳар гӯшаи ҷаҳон идора мешаванд.</p><div className="actions"><a className="primary" href="#projects">Дидани лоиҳаҳо →</a><a className="secondary" href="#contact">Бо ман тамос гиред</a></div></div>
      <aside className="profileCard"><img src="/gafur.jpg" alt="Ғафурҷон Уайдулоев"/><p><b>Барномасози худомӯз</b><br/>Муҳандиси сохтмонӣ</p><div className="metrics"><div><b>7+</b><span>лоиҳаи амалӣ</span></div><div><b>2004</b><span>соли таваллуд</span></div></div></aside>
    </section>
    <section className="skillbar" aria-label="Малакаҳои техникӣ"><div className="skillTrack">{[...skills,...skills].map((x,i)=><span key={`${x}-${i}`}>{x}<i>◆</i></span>)}</div></section>
    <section className="about shell" id="about"><p className="sectionNo">01 / Дар бораи ман</p><h2>Аз шавқи наврасӣ<br/>то маҳсулоти воқеӣ.</h2><div className="aboutText"><p>Ман 19 июни соли 2004 таваллуд шудаам. Барномасозиро аз синфи 8, бе омӯзгори шахсӣ, мустақилона оғоз кардам. Аввал HTML, CSS ва JavaScript-ро омӯхтам, баъдан ба Node.js, PHP, SQL, MySQL, C# ва технологияҳои серверӣ гузаштам.</p><p>Имрӯз ман метавонам маҳсулотро аз идея то барномаи корӣ расонам: интерфейс созам, базаи маълумот тарҳрезӣ кунам, сервер ва доменро пайваст намоям, лоиҳаро дар GitHub идора кунам ва барои истифодабарандаи воқеӣ омода созам.</p></div></section>
    <section className="showcase"><div className="shell"><div><p className="sectionNo dark">МАҲСУЛОТИ АМАЛӢ</p><h2>TOJ POS — идораи тиҷорат дар як система.</h2><p>Барнома барои нуқтаи фурӯш, панели маъмур, анбор ва назорати телефонӣ сохта шудааст. Соҳибкор метавонад фурӯш, фоида, чекҳо, молҳои каммонда ва фаъолияти кассирҳоро аз дур бинад.</p></div><img src="/tojpos-admin-web.jpg" alt="Панели маъмурии TOJ POS"/></div></section>
    <section className="projects shell" id="projects"><p className="sectionNo">02 / Лоиҳаҳои интихобшуда</p><div className="projectGrid">{projects.map((p,i)=><article className={p.featured?"featured":""} key={p.name}><span>{String(i+1).padStart(2,"0")} · {p.tag}</span>{p.image&&<img src={p.image} alt={`Интерфейси ${p.name}`}/>}<h3>{p.name}</h3><p>{p.text}</p><small>{p.tech}</small></article>)}</div></section>
    <section className="journey shell" id="journey"><p className="sectionNo">03 / Роҳи таҳсил ва кор</p><div className="timeline"><div><b>2021</b><h3>Оғози таҳсилоти касбӣ</h3><p>Пас аз хатми синфи 9-и МТМУ №52-и шаҳри Ҳисор, ба Коллеҷи муҳандисию омӯзгории шаҳри Душанбе дохил шуда, чор сол аз рӯи буҷет таҳсил кардам.</p></div><div><b>Омӯзгорӣ</b><h3>Технологияи иттилоотӣ</h3><p>Аз курси 4 ҳамчун омӯзгор дар Литсейи касбӣ-техникии шаҳри Ҳисор корро оғоз намуда, баъдан дар МТМУ №52 ва мактаби русии №1 таҷрибаи омӯзгорӣ гирифтам.</p></div><div><b>2025–2026</b><h3>Аз код то сервер</h3><p>GitHub, Render, доменҳо ва ҷойгиркунии сервериро омӯхтам. TOJ POS-ро ба маҳсулоти дорои муштарӣ табдил дода, фаъолияти мустақили худро оғоз кардам.</p></div></div></section>
    <section className="mobileDemo shell"><img src="/tojpos-mobile-web.jpg" alt="TOJ POS дар телефон"/><div><p className="sectionNo">ДАР ҲАР ҶО</p><h2>Назорат аз телефон.</h2><p>TOJ POS маълумоти тиҷоратро ба телефони соҳибкор мерасонад: фурӯши имрӯз, чекҳо, фоидаи соф, молҳои каммонда, сменаҳо ва амалиётҳои охирин.</p></div></section>
    <section className="waiterDemo shell"><div><p className="sectionNo">ФАРМОИШГИРИИ ЗУД</p><h2>Официант фармоишро бе таъхир қабул мекунад.</h2><p>Меню бо гурӯҳҳо ва ҷустуҷӯ фавран дастрас аст. Официант маҳсулотро интихоб мекунад, миз ё навъи фармоишро муайян месозад ва фармоишро ба ошхона мефиристад. Маълумот ба касса ва панели маъмур ҳамзамон мерасад.</p><ul><li>Интихоби тези маҳсулот</li><li>Ҳисоби автоматии маблағ</li><li>Пайвастшавӣ бо касса ва ошхона</li></ul></div><div className="deviceStage"><div className="tablet"><span className="camera"/><img src="/tojpos-cashier-web.jpg" alt="Қисми фармоишгирии официанти TOJ POS"/></div><div className="phone"><img src="/tojpos-mobile-web.jpg" alt="Назорати TOJ POS аз телефон"/></div></div></section>
    <footer id="contact"><div className="shell"><p className="sectionNo">04 / Тамос</p><h2>Бо мо<br/><em>пешрафт кунед.</em></h2><p className="footerLead">Барои автоматизатсияи кафе, ошхона, мағоза, дорухона ё сохтани системаи махсус бо ман дар тамос шавед. Мо идеяи шуморо ба маҳсулоти воқеӣ ва корӣ табдил медиҳем.</p><div className="contacts"><a href="https://wa.me/992001666922">WhatsApp <b>001 666 922</b></a><a href="https://t.me/+992001666922">Telegram <b>001 666 922</b></a><a href="https://instagram.com/tojpos.official">Instagram <b>@tojpos.official</b></a><a href="mailto:ubajdulloevbdugafur@gmail.com">Почта <b>ubajdulloevbdugafur@gmail.com</b></a><a href="https://github.com/gafur486">GitHub <b>@gafur486</b></a></div><p className="copy">© 2026 Ғафурҷон Уайдулоев</p></div></footer>
  </main>;
}

